dependencies {
    implementation project(':cs-application')
    implementation project(':cs-domain')
    implementation "org.springframework:spring-context:${springFrameworkVersion}"
    implementation 'org.springframework.data:spring-data-jpa:3.3.5'
    implementation 'org.springframework:spring-tx:6.1.14'
    implementation 'jakarta.persistence:jakarta.persistence-api:3.1.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.2'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.17.2'

    compileOnly 'org.projectlombok:lombok:1.18.34'
    annotationProcessor 'org.projectlombok:lombok:1.18.34'

    testImplementation "org.junit.jupiter:junit-jupiter:${junitVersion}"
    testImplementation "org.assertj:assertj-core:${assertjVersion}"
    testImplementation "org.mockito:mockito-junit-jupiter:${mockitoVersion}"
}
