dependencies {
    implementation project(':cs-application')
    implementation "org.springframework:spring-web:${springFrameworkVersion}"
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    testImplementation "org.junit.jupiter:junit-jupiter:${junitVersion}"
    testImplementation "org.assertj:assertj-core:${assertjVersion}"
    testImplementation "org.mockito:mockito-junit-jupiter:${mockitoVersion}"
}
