dependencies {
    implementation project(':cs-application')
    implementation "org.springframework:spring-web:${springFrameworkVersion}"

    testImplementation "org.junit.jupiter:junit-jupiter:${junitVersion}"
    testImplementation "org.assertj:assertj-core:${assertjVersion}"
    testImplementation "org.mockito:mockito-junit-jupiter:${mockitoVersion}"
}
